/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtivarRouteImport } from './routes/ativar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQrCodesRouteImport } from './routes/_authenticated/qr-codes'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags.index'
import { Route as AuthenticatedPecasIndexRouteImport } from './routes/_authenticated/pecas.index'
import { Route as TIdViewRouteImport } from './routes/t.$id_.view'
import { Route as AuthenticatedTagsNewRouteImport } from './routes/_authenticated/tags.new'
import { Route as AuthenticatedTagsIdRouteImport } from './routes/_authenticated/tags.$id'
import { Route as AuthenticatedPecasIdRouteImport } from './routes/_authenticated/pecas.$id'
import { Route as AuthenticatedLandingTagIdRouteImport } from './routes/_authenticated/landing.$tagId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarRoute = AtivarRouteImport.update({
  id: '/ativar',
  path: '/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrCodesRoute = AuthenticatedQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const AuthenticatedPecasIndexRoute = AuthenticatedPecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TIdViewRoute = TIdViewRouteImport.update({
  id: '/t/$id_/view',
  path: '/t/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagsNewRoute = AuthenticatedTagsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const AuthenticatedTagsIdRoute = AuthenticatedTagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const AuthenticatedPecasIdRoute = AuthenticatedPecasIdRouteImport.update({
  id: '/pecas/$id',
  path: '/pecas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandingTagIdRoute =
  AuthenticatedLandingTagIdRouteImport.update({
    id: '/landing/$tagId',
    path: '/landing/$tagId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/t/$id': typeof TIdRoute
  '/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id/view': typeof TIdViewRoute
  '/pecas/': typeof AuthenticatedPecasIndexRoute
  '/tags/': typeof AuthenticatedTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/t/$id': typeof TIdRoute
  '/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id/view': typeof TIdViewRoute
  '/pecas': typeof AuthenticatedPecasIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/qr-codes': typeof AuthenticatedQrCodesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/t/$id': typeof TIdRoute
  '/_authenticated/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/_authenticated/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/_authenticated/tags/$id': typeof AuthenticatedTagsIdRoute
  '/_authenticated/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id_/view': typeof TIdViewRoute
  '/_authenticated/pecas/': typeof AuthenticatedPecasIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/automations'
    | '/dashboard'
    | '/integrations'
    | '/leads'
    | '/links'
    | '/qr-codes'
    | '/settings'
    | '/tags'
    | '/team'
    | '/t/$id'
    | '/landing/$tagId'
    | '/pecas/$id'
    | '/tags/$id'
    | '/tags/new'
    | '/t/$id/view'
    | '/pecas/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/automations'
    | '/dashboard'
    | '/integrations'
    | '/leads'
    | '/links'
    | '/qr-codes'
    | '/settings'
    | '/team'
    | '/t/$id'
    | '/landing/$tagId'
    | '/pecas/$id'
    | '/tags/$id'
    | '/tags/new'
    | '/t/$id/view'
    | '/pecas'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/automations'
    | '/_authenticated/dashboard'
    | '/_authenticated/integrations'
    | '/_authenticated/leads'
    | '/_authenticated/links'
    | '/_authenticated/qr-codes'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
    | '/_authenticated/team'
    | '/t/$id'
    | '/_authenticated/landing/$tagId'
    | '/_authenticated/pecas/$id'
    | '/_authenticated/tags/$id'
    | '/_authenticated/tags/new'
    | '/t/$id_/view'
    | '/_authenticated/pecas/'
    | '/_authenticated/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtivarRoute: typeof AtivarRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TIdRoute: typeof TIdRoute
  TIdViewRoute: typeof TIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar': {
      id: '/ativar'
      path: '/ativar'
      fullPath: '/ativar'
      preLoaderRoute: typeof AtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-codes': {
      id: '/_authenticated/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof AuthenticatedQrCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/_authenticated/pecas/': {
      id: '/_authenticated/pecas/'
      path: '/pecas'
      fullPath: '/pecas/'
      preLoaderRoute: typeof AuthenticatedPecasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$id_/view': {
      id: '/t/$id_/view'
      path: '/t/$id/view'
      fullPath: '/t/$id/view'
      preLoaderRoute: typeof TIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tags/new': {
      id: '/_authenticated/tags/new'
      path: '/new'
      fullPath: '/tags/new'
      preLoaderRoute: typeof AuthenticatedTagsNewRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/_authenticated/tags/$id': {
      id: '/_authenticated/tags/$id'
      path: '/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof AuthenticatedTagsIdRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/_authenticated/pecas/$id': {
      id: '/_authenticated/pecas/$id'
      path: '/pecas/$id'
      fullPath: '/pecas/$id'
      preLoaderRoute: typeof AuthenticatedPecasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/$tagId': {
      id: '/_authenticated/landing/$tagId'
      path: '/landing/$tagId'
      fullPath: '/landing/$tagId'
      preLoaderRoute: typeof AuthenticatedLandingTagIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTagsRouteChildren {
  AuthenticatedTagsIdRoute: typeof AuthenticatedTagsIdRoute
  AuthenticatedTagsNewRoute: typeof AuthenticatedTagsNewRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
}

const AuthenticatedTagsRouteChildren: AuthenticatedTagsRouteChildren = {
  AuthenticatedTagsIdRoute: AuthenticatedTagsIdRoute,
  AuthenticatedTagsNewRoute: AuthenticatedTagsNewRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
}

const AuthenticatedTagsRouteWithChildren =
  AuthenticatedTagsRoute._addFileChildren(AuthenticatedTagsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedQrCodesRoute: typeof AuthenticatedQrCodesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedLandingTagIdRoute: typeof AuthenticatedLandingTagIdRoute
  AuthenticatedPecasIdRoute: typeof AuthenticatedPecasIdRoute
  AuthenticatedPecasIndexRoute: typeof AuthenticatedPecasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedQrCodesRoute: AuthenticatedQrCodesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedLandingTagIdRoute: AuthenticatedLandingTagIdRoute,
  AuthenticatedPecasIdRoute: AuthenticatedPecasIdRoute,
  AuthenticatedPecasIndexRoute: AuthenticatedPecasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtivarRoute: AtivarRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TIdRoute: TIdRoute,
  TIdViewRoute: TIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
