/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AtivarRouteImport } from './routes/ativar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedCalculadoraCustosRouteImport } from './routes/_authenticated/calculadora-custos'
import { Route as AuthenticatedCriadorEnvelopesRouteImport } from './routes/_authenticated/criador-envelopes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEstudioBonecosRouteImport } from './routes/_authenticated/estudio-bonecos'
import { Route as AuthenticatedEtiquetaPlanaRouteImport } from './routes/_authenticated/etiqueta-plana'
import { Route as AuthenticatedGanchosRouteImport } from './routes/_authenticated/ganchos'
import { Route as AuthenticatedGerador3dRouteImport } from './routes/_authenticated/gerador-3d'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedKitPinturaRouteImport } from './routes/_authenticated/kit-pintura'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated/links'
import { Route as AuthenticatedMoldeSiliconeRouteImport } from './routes/_authenticated/molde-silicone'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPetTagRouteImport } from './routes/_authenticated/pet-tag'
import { Route as AuthenticatedPlacaPixRouteImport } from './routes/_authenticated/placa-pix'
import { Route as AuthenticatedQrCodesRouteImport } from './routes/_authenticated/qr-codes'
import { Route as AuthenticatedQrKidsRouteImport } from './routes/_authenticated/qr-kids'
import { Route as AuthenticatedQuebraCabecaMontessoriRouteImport } from './routes/_authenticated/quebra-cabeca-montessori'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AtivarIdRouteImport } from './routes/ativar_.$id'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as AuthenticatedConfigurarIdRouteImport } from './routes/_authenticated/configurar.$id'
import { Route as AuthenticatedLandingTagIdRouteImport } from './routes/_authenticated/landing.$tagId'
import { Route as AuthenticatedPecasIndexRouteImport } from './routes/_authenticated/pecas.index'
import { Route as AuthenticatedPecasIdRouteImport } from './routes/_authenticated/pecas.$id'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags.index'
import { Route as AuthenticatedTagsIdRouteImport } from './routes/_authenticated/tags.$id'
import { Route as AuthenticatedTagsNewRouteImport } from './routes/_authenticated/tags.new'
import { Route as TIdViewRouteImport } from './routes/t.$id_.view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivarRoute = AtivarRouteImport.update({
  id: '/ativar',
  path: '/ativar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalculadoraCustosRoute =
  AuthenticatedCalculadoraCustosRouteImport.update({
    id: '/calculadora-custos',
    path: '/calculadora-custos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCriadorEnvelopesRoute =
  AuthenticatedCriadorEnvelopesRouteImport.update({
    id: '/criador-envelopes',
    path: '/criador-envelopes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstudioBonecosRoute =
  AuthenticatedEstudioBonecosRouteImport.update({
    id: '/estudio-bonecos',
    path: '/estudio-bonecos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtiquetaPlanaRoute =
  AuthenticatedEtiquetaPlanaRouteImport.update({
    id: '/etiqueta-plana',
    path: '/etiqueta-plana',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGanchosRoute = AuthenticatedGanchosRouteImport.update({
  id: '/ganchos',
  path: '/ganchos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerador3dRoute = AuthenticatedGerador3dRouteImport.update({
  id: '/gerador-3d',
  path: '/gerador-3d',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKitPinturaRoute = AuthenticatedKitPinturaRouteImport.update({
  id: '/kit-pintura',
  path: '/kit-pintura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoldeSiliconeRoute =
  AuthenticatedMoldeSiliconeRouteImport.update({
    id: '/molde-silicone',
    path: '/molde-silicone',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetTagRoute = AuthenticatedPetTagRouteImport.update({
  id: '/pet-tag',
  path: '/pet-tag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlacaPixRoute = AuthenticatedPlacaPixRouteImport.update({
  id: '/placa-pix',
  path: '/placa-pix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrCodesRoute = AuthenticatedQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrKidsRoute = AuthenticatedQrKidsRouteImport.update({
  id: '/qr-kids',
  path: '/qr-kids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuebraCabecaMontessoriRoute =
  AuthenticatedQuebraCabecaMontessoriRouteImport.update({
    id: '/quebra-cabeca-montessori',
    path: '/quebra-cabeca-montessori',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AtivarIdRoute = AtivarIdRouteImport.update({
  id: '/ativar_/$id',
  path: '/ativar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfigurarIdRoute =
  AuthenticatedConfigurarIdRouteImport.update({
    id: '/configurar/$id',
    path: '/configurar/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingTagIdRoute =
  AuthenticatedLandingTagIdRouteImport.update({
    id: '/landing/$tagId',
    path: '/landing/$tagId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPecasIndexRoute = AuthenticatedPecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecasIdRoute = AuthenticatedPecasIdRouteImport.update({
  id: '/pecas/$id',
  path: '/pecas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const AuthenticatedTagsIdRoute = AuthenticatedTagsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const AuthenticatedTagsNewRoute = AuthenticatedTagsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedTagsRoute,
} as any)
const TIdViewRoute = TIdViewRouteImport.update({
  id: '/t/$id_/view',
  path: '/t/$id/view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/calculadora-custos': typeof AuthenticatedCalculadoraCustosRoute
  '/criador-envelopes': typeof AuthenticatedCriadorEnvelopesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estudio-bonecos': typeof AuthenticatedEstudioBonecosRoute
  '/etiqueta-plana': typeof AuthenticatedEtiquetaPlanaRoute
  '/ganchos': typeof AuthenticatedGanchosRoute
  '/gerador-3d': typeof AuthenticatedGerador3dRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kit-pintura': typeof AuthenticatedKitPinturaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/molde-silicone': typeof AuthenticatedMoldeSiliconeRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pet-tag': typeof AuthenticatedPetTagRoute
  '/placa-pix': typeof AuthenticatedPlacaPixRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/qr-kids': typeof AuthenticatedQrKidsRoute
  '/quebra-cabeca-montessori': typeof AuthenticatedQuebraCabecaMontessoriRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/ativar/$id': typeof AtivarIdRoute
  '/t/$id': typeof TIdRoute
  '/configurar/$id': typeof AuthenticatedConfigurarIdRoute
  '/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id/view': typeof TIdViewRoute
  '/pecas/': typeof AuthenticatedPecasIndexRoute
  '/tags/': typeof AuthenticatedTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/calculadora-custos': typeof AuthenticatedCalculadoraCustosRoute
  '/criador-envelopes': typeof AuthenticatedCriadorEnvelopesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estudio-bonecos': typeof AuthenticatedEstudioBonecosRoute
  '/etiqueta-plana': typeof AuthenticatedEtiquetaPlanaRoute
  '/ganchos': typeof AuthenticatedGanchosRoute
  '/gerador-3d': typeof AuthenticatedGerador3dRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kit-pintura': typeof AuthenticatedKitPinturaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/molde-silicone': typeof AuthenticatedMoldeSiliconeRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pet-tag': typeof AuthenticatedPetTagRoute
  '/placa-pix': typeof AuthenticatedPlacaPixRoute
  '/qr-codes': typeof AuthenticatedQrCodesRoute
  '/qr-kids': typeof AuthenticatedQrKidsRoute
  '/quebra-cabeca-montessori': typeof AuthenticatedQuebraCabecaMontessoriRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/ativar/$id': typeof AtivarIdRoute
  '/t/$id': typeof TIdRoute
  '/configurar/$id': typeof AuthenticatedConfigurarIdRoute
  '/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/tags/$id': typeof AuthenticatedTagsIdRoute
  '/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id/view': typeof TIdViewRoute
  '/pecas': typeof AuthenticatedPecasIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ativar': typeof AtivarRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/calculadora-custos': typeof AuthenticatedCalculadoraCustosRoute
  '/_authenticated/criador-envelopes': typeof AuthenticatedCriadorEnvelopesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estudio-bonecos': typeof AuthenticatedEstudioBonecosRoute
  '/_authenticated/etiqueta-plana': typeof AuthenticatedEtiquetaPlanaRoute
  '/_authenticated/ganchos': typeof AuthenticatedGanchosRoute
  '/_authenticated/gerador-3d': typeof AuthenticatedGerador3dRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/kit-pintura': typeof AuthenticatedKitPinturaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/molde-silicone': typeof AuthenticatedMoldeSiliconeRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pet-tag': typeof AuthenticatedPetTagRoute
  '/_authenticated/placa-pix': typeof AuthenticatedPlacaPixRoute
  '/_authenticated/qr-codes': typeof AuthenticatedQrCodesRoute
  '/_authenticated/qr-kids': typeof AuthenticatedQrKidsRoute
  '/_authenticated/quebra-cabeca-montessori': typeof AuthenticatedQuebraCabecaMontessoriRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/ativar_/$id': typeof AtivarIdRoute
  '/t/$id': typeof TIdRoute
  '/_authenticated/configurar/$id': typeof AuthenticatedConfigurarIdRoute
  '/_authenticated/landing/$tagId': typeof AuthenticatedLandingTagIdRoute
  '/_authenticated/pecas/$id': typeof AuthenticatedPecasIdRoute
  '/_authenticated/tags/$id': typeof AuthenticatedTagsIdRoute
  '/_authenticated/tags/new': typeof AuthenticatedTagsNewRoute
  '/t/$id_/view': typeof TIdViewRoute
  '/_authenticated/pecas/': typeof AuthenticatedPecasIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/automations'
    | '/calculadora-custos'
    | '/criador-envelopes'
    | '/dashboard'
    | '/estudio-bonecos'
    | '/etiqueta-plana'
    | '/ganchos'
    | '/gerador-3d'
    | '/integrations'
    | '/kit-pintura'
    | '/leads'
    | '/links'
    | '/molde-silicone'
    | '/notificacoes'
    | '/pet-tag'
    | '/placa-pix'
    | '/qr-codes'
    | '/qr-kids'
    | '/quebra-cabeca-montessori'
    | '/settings'
    | '/tags'
    | '/team'
    | '/ativar/$id'
    | '/t/$id'
    | '/configurar/$id'
    | '/landing/$tagId'
    | '/pecas/$id'
    | '/tags/$id'
    | '/tags/new'
    | '/t/$id/view'
    | '/pecas/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/automations'
    | '/calculadora-custos'
    | '/criador-envelopes'
    | '/dashboard'
    | '/estudio-bonecos'
    | '/etiqueta-plana'
    | '/ganchos'
    | '/gerador-3d'
    | '/integrations'
    | '/kit-pintura'
    | '/leads'
    | '/links'
    | '/molde-silicone'
    | '/notificacoes'
    | '/pet-tag'
    | '/placa-pix'
    | '/qr-codes'
    | '/qr-kids'
    | '/quebra-cabeca-montessori'
    | '/settings'
    | '/team'
    | '/ativar/$id'
    | '/t/$id'
    | '/configurar/$id'
    | '/landing/$tagId'
    | '/pecas/$id'
    | '/tags/$id'
    | '/tags/new'
    | '/t/$id/view'
    | '/pecas'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativar'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/automations'
    | '/_authenticated/calculadora-custos'
    | '/_authenticated/criador-envelopes'
    | '/_authenticated/dashboard'
    | '/_authenticated/estudio-bonecos'
    | '/_authenticated/etiqueta-plana'
    | '/_authenticated/ganchos'
    | '/_authenticated/gerador-3d'
    | '/_authenticated/integrations'
    | '/_authenticated/kit-pintura'
    | '/_authenticated/leads'
    | '/_authenticated/links'
    | '/_authenticated/molde-silicone'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pet-tag'
    | '/_authenticated/placa-pix'
    | '/_authenticated/qr-codes'
    | '/_authenticated/qr-kids'
    | '/_authenticated/quebra-cabeca-montessori'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
    | '/_authenticated/team'
    | '/ativar_/$id'
    | '/t/$id'
    | '/_authenticated/configurar/$id'
    | '/_authenticated/landing/$tagId'
    | '/_authenticated/pecas/$id'
    | '/_authenticated/tags/$id'
    | '/_authenticated/tags/new'
    | '/t/$id_/view'
    | '/_authenticated/pecas/'
    | '/_authenticated/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtivarRoute: typeof AtivarRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AtivarIdRoute: typeof AtivarIdRoute
  TIdRoute: typeof TIdRoute
  TIdViewRoute: typeof TIdViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativar': {
      id: '/ativar'
      path: '/ativar'
      fullPath: '/ativar'
      preLoaderRoute: typeof AtivarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora-custos': {
      id: '/_authenticated/calculadora-custos'
      path: '/calculadora-custos'
      fullPath: '/calculadora-custos'
      preLoaderRoute: typeof AuthenticatedCalculadoraCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criador-envelopes': {
      id: '/_authenticated/criador-envelopes'
      path: '/criador-envelopes'
      fullPath: '/criador-envelopes'
      preLoaderRoute: typeof AuthenticatedCriadorEnvelopesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudio-bonecos': {
      id: '/_authenticated/estudio-bonecos'
      path: '/estudio-bonecos'
      fullPath: '/estudio-bonecos'
      preLoaderRoute: typeof AuthenticatedEstudioBonecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiqueta-plana': {
      id: '/_authenticated/etiqueta-plana'
      path: '/etiqueta-plana'
      fullPath: '/etiqueta-plana'
      preLoaderRoute: typeof AuthenticatedEtiquetaPlanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ganchos': {
      id: '/_authenticated/ganchos'
      path: '/ganchos'
      fullPath: '/ganchos'
      preLoaderRoute: typeof AuthenticatedGanchosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerador-3d': {
      id: '/_authenticated/gerador-3d'
      path: '/gerador-3d'
      fullPath: '/gerador-3d'
      preLoaderRoute: typeof AuthenticatedGerador3dRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kit-pintura': {
      id: '/_authenticated/kit-pintura'
      path: '/kit-pintura'
      fullPath: '/kit-pintura'
      preLoaderRoute: typeof AuthenticatedKitPinturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/molde-silicone': {
      id: '/_authenticated/molde-silicone'
      path: '/molde-silicone'
      fullPath: '/molde-silicone'
      preLoaderRoute: typeof AuthenticatedMoldeSiliconeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet-tag': {
      id: '/_authenticated/pet-tag'
      path: '/pet-tag'
      fullPath: '/pet-tag'
      preLoaderRoute: typeof AuthenticatedPetTagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placa-pix': {
      id: '/_authenticated/placa-pix'
      path: '/placa-pix'
      fullPath: '/placa-pix'
      preLoaderRoute: typeof AuthenticatedPlacaPixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-codes': {
      id: '/_authenticated/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof AuthenticatedQrCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-kids': {
      id: '/_authenticated/qr-kids'
      path: '/qr-kids'
      fullPath: '/qr-kids'
      preLoaderRoute: typeof AuthenticatedQrKidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quebra-cabeca-montessori': {
      id: '/_authenticated/quebra-cabeca-montessori'
      path: '/quebra-cabeca-montessori'
      fullPath: '/quebra-cabeca-montessori'
      preLoaderRoute: typeof AuthenticatedQuebraCabecaMontessoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ativar_/$id': {
      id: '/ativar_/$id'
      path: '/ativar/$id'
      fullPath: '/ativar/$id'
      preLoaderRoute: typeof AtivarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configurar/$id': {
      id: '/_authenticated/configurar/$id'
      path: '/configurar/$id'
      fullPath: '/configurar/$id'
      preLoaderRoute: typeof AuthenticatedConfigurarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/$tagId': {
      id: '/_authenticated/landing/$tagId'
      path: '/landing/$tagId'
      fullPath: '/landing/$tagId'
      preLoaderRoute: typeof AuthenticatedLandingTagIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas/': {
      id: '/_authenticated/pecas/'
      path: '/pecas'
      fullPath: '/pecas/'
      preLoaderRoute: typeof AuthenticatedPecasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas/$id': {
      id: '/_authenticated/pecas/$id'
      path: '/pecas/$id'
      fullPath: '/pecas/$id'
      preLoaderRoute: typeof AuthenticatedPecasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/_authenticated/tags/$id': {
      id: '/_authenticated/tags/$id'
      path: '/$id'
      fullPath: '/tags/$id'
      preLoaderRoute: typeof AuthenticatedTagsIdRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/_authenticated/tags/new': {
      id: '/_authenticated/tags/new'
      path: '/new'
      fullPath: '/tags/new'
      preLoaderRoute: typeof AuthenticatedTagsNewRouteImport
      parentRoute: typeof AuthenticatedTagsRoute
    }
    '/t/$id_/view': {
      id: '/t/$id_/view'
      path: '/t/$id/view'
      fullPath: '/t/$id/view'
      preLoaderRoute: typeof TIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedTagsRouteChildren {
  AuthenticatedTagsIdRoute: typeof AuthenticatedTagsIdRoute
  AuthenticatedTagsNewRoute: typeof AuthenticatedTagsNewRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
}

const AuthenticatedTagsRouteChildren: AuthenticatedTagsRouteChildren = {
  AuthenticatedTagsIdRoute: AuthenticatedTagsIdRoute,
  AuthenticatedTagsNewRoute: AuthenticatedTagsNewRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
}

const AuthenticatedTagsRouteWithChildren =
  AuthenticatedTagsRoute._addFileChildren(AuthenticatedTagsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedCalculadoraCustosRoute: typeof AuthenticatedCalculadoraCustosRoute
  AuthenticatedCriadorEnvelopesRoute: typeof AuthenticatedCriadorEnvelopesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstudioBonecosRoute: typeof AuthenticatedEstudioBonecosRoute
  AuthenticatedEtiquetaPlanaRoute: typeof AuthenticatedEtiquetaPlanaRoute
  AuthenticatedGanchosRoute: typeof AuthenticatedGanchosRoute
  AuthenticatedGerador3dRoute: typeof AuthenticatedGerador3dRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKitPinturaRoute: typeof AuthenticatedKitPinturaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedMoldeSiliconeRoute: typeof AuthenticatedMoldeSiliconeRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPetTagRoute: typeof AuthenticatedPetTagRoute
  AuthenticatedPlacaPixRoute: typeof AuthenticatedPlacaPixRoute
  AuthenticatedQrCodesRoute: typeof AuthenticatedQrCodesRoute
  AuthenticatedQrKidsRoute: typeof AuthenticatedQrKidsRoute
  AuthenticatedQuebraCabecaMontessoriRoute: typeof AuthenticatedQuebraCabecaMontessoriRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedConfigurarIdRoute: typeof AuthenticatedConfigurarIdRoute
  AuthenticatedLandingTagIdRoute: typeof AuthenticatedLandingTagIdRoute
  AuthenticatedPecasIdRoute: typeof AuthenticatedPecasIdRoute
  AuthenticatedPecasIndexRoute: typeof AuthenticatedPecasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedCalculadoraCustosRoute: AuthenticatedCalculadoraCustosRoute,
  AuthenticatedCriadorEnvelopesRoute: AuthenticatedCriadorEnvelopesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstudioBonecosRoute: AuthenticatedEstudioBonecosRoute,
  AuthenticatedEtiquetaPlanaRoute: AuthenticatedEtiquetaPlanaRoute,
  AuthenticatedGanchosRoute: AuthenticatedGanchosRoute,
  AuthenticatedGerador3dRoute: AuthenticatedGerador3dRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKitPinturaRoute: AuthenticatedKitPinturaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedMoldeSiliconeRoute: AuthenticatedMoldeSiliconeRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPetTagRoute: AuthenticatedPetTagRoute,
  AuthenticatedPlacaPixRoute: AuthenticatedPlacaPixRoute,
  AuthenticatedQrCodesRoute: AuthenticatedQrCodesRoute,
  AuthenticatedQrKidsRoute: AuthenticatedQrKidsRoute,
  AuthenticatedQuebraCabecaMontessoriRoute:
    AuthenticatedQuebraCabecaMontessoriRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedConfigurarIdRoute: AuthenticatedConfigurarIdRoute,
  AuthenticatedLandingTagIdRoute: AuthenticatedLandingTagIdRoute,
  AuthenticatedPecasIdRoute: AuthenticatedPecasIdRoute,
  AuthenticatedPecasIndexRoute: AuthenticatedPecasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtivarRoute: AtivarRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AtivarIdRoute: AtivarIdRoute,
  TIdRoute: TIdRoute,
  TIdViewRoute: TIdViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
